### ISSUE TITLE
Logins not saving

### ISSUE THREAD

**Issue by helpimnotdrowning** [openwanderer/example-app#3]
When I make an account with the full app, it accepts the login fine and well, no complaints in the Apache `error.log` and the Chrome console shows no problems either. But when I go to sign back in with my newly created account, it tells me I'm using the wrong username/password. I make an account  nhdhdh@h.com : aaaaaaaaaaa  and copy+paste the info, but it still tells me it's wrong. If I use pgAdmin and look at the users table, it's empty.

**Comment by helpimnotdrowning** [comment]
nevermind, 10 seconds after opening this issue i alt tabbed back into the page and clicked login. it worked somehow.

**Comment by nickw1** [comment]
Glad it works. Maybe a caching issue?
